name: Build resume
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:TL2023-historic
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Compile
      run: xelatex resume.tex
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: resume.pdf
    - name: "Generate build tag"
      run: |
        echo "tag="resume-$(date +'%Y-%m-%d-%H%M')"" >> $GITHUB_OUTPUT
      id: version
    - name: "Rename file"
      run: |
        mv resume.pdf ${{ steps.version.outputs.tag }}.pdf
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: ${{ steps.version.outputs.tag }}
        files: |
          ${{ steps.version.outputs.tag }}.pdf